/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as HeroesIndexImport } from './routes/heroes/index'
import { Route as HeroesHeroIdImport } from './routes/heroes/$heroId'

// Create Virtual Routes

const HeroesLazyImport = createFileRoute('/heroes')()

// Create/Update Routes

const HeroesLazyRoute = HeroesLazyImport.update({
  path: '/heroes',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/heroes.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HeroesIndexRoute = HeroesIndexImport.update({
  path: '/',
  getParentRoute: () => HeroesLazyRoute,
} as any)

const HeroesHeroIdRoute = HeroesHeroIdImport.update({
  path: '/$heroId',
  getParentRoute: () => HeroesLazyRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/heroes': {
      id: '/heroes'
      path: '/heroes'
      fullPath: '/heroes'
      preLoaderRoute: typeof HeroesLazyImport
      parentRoute: typeof rootRoute
    }
    '/heroes/$heroId': {
      id: '/heroes/$heroId'
      path: '/$heroId'
      fullPath: '/heroes/$heroId'
      preLoaderRoute: typeof HeroesHeroIdImport
      parentRoute: typeof HeroesLazyImport
    }
    '/heroes/': {
      id: '/heroes/'
      path: '/'
      fullPath: '/heroes/'
      preLoaderRoute: typeof HeroesIndexImport
      parentRoute: typeof HeroesLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  HeroesLazyRoute: HeroesLazyRoute.addChildren({
    HeroesHeroIdRoute,
    HeroesIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/heroes"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/heroes": {
      "filePath": "heroes.lazy.tsx",
      "children": [
        "/heroes/$heroId",
        "/heroes/"
      ]
    },
    "/heroes/$heroId": {
      "filePath": "heroes/$heroId.tsx",
      "parent": "/heroes"
    },
    "/heroes/": {
      "filePath": "heroes/index.tsx",
      "parent": "/heroes"
    }
  }
}
ROUTE_MANIFEST_END */
