/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HeroesImport } from './routes/heroes'
import { Route as IndexImport } from './routes/index'
import { Route as HeroesHeroIdImport } from './routes/heroes/$heroId'

// Create/Update Routes

const HeroesRoute = HeroesImport.update({
  path: '/heroes',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/heroes.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HeroesHeroIdRoute = HeroesHeroIdImport.update({
  path: '/$heroId',
  getParentRoute: () => HeroesRoute,
} as any).lazy(() =>
  import('./routes/heroes/$heroId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/heroes': {
      id: '/heroes'
      path: '/heroes'
      fullPath: '/heroes'
      preLoaderRoute: typeof HeroesImport
      parentRoute: typeof rootRoute
    }
    '/heroes/$heroId': {
      id: '/heroes/$heroId'
      path: '/$heroId'
      fullPath: '/heroes/$heroId'
      preLoaderRoute: typeof HeroesHeroIdImport
      parentRoute: typeof HeroesImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  HeroesRoute: HeroesRoute.addChildren({ HeroesHeroIdRoute }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/heroes"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/heroes": {
      "filePath": "heroes.tsx",
      "children": [
        "/heroes/$heroId"
      ]
    },
    "/heroes/$heroId": {
      "filePath": "heroes/$heroId.tsx",
      "parent": "/heroes"
    }
  }
}
ROUTE_MANIFEST_END */
